vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO GuillaumeLaurin/Cest
    REF "v${VERSION}"
    SHA512 0
    HEAD_REF main
)

set(CEST_CMAKE_OPTIONS)
if("debug" IN_LIST FEATURES)
    list(APPEND CEST_CMAKE_OPTIONS --log-level=DEBUG --log-context)
endif()

vcpkg_cmake_configure(
  SOURCE_PATH "${SOURCE_PATH}"
  OPTIONS
  ${CEST_CMAKE_OPTIONS}
  -DCMAKE_CXX_SCAN_FOR_MODULES:BOOL=OFF
  -DCMAKE_EXPORT_PACKAGE_REGISTRY:BOOL=OFF
  -DBUILD_TESTS:BOOL=OFF
  -DBUILD_TREE_DEPLOY:BOOL=OFF
  -DCEST_EXAMPLE:BOOL=OFF
  -DCEST_PORT:STRING=${PORT}
  -DCEST_VCPKG:BOOL=ON
  -DVERBOSE_CONFIGURE:BOOL=ON
  ${FEATURE_OPTIONS}
)

vcpkg_cmake_install()

file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/debug/include")

vcpkg_cmake_config_fixup()

file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/debug")

vcpkg_install_copyright(FILE_LIST "${SOURCE_PATH}/LICENSE.md")